### ISSUE TITLE
Spanish translation is too long

### ISSUE THREAD

**Issue by RevoArma3** [RevoArma3/3den-Enhanced-Translation#13]
There are some translations which do not fit the controls. See Preferences.

Any chance those could be shortened? Maybe use abbreviations?

**Comment by arv187** [comment]
Can you tell me what lines exactly to check it? Only preferences?

**Comment by arv187** [comment]
Ok, I see 

> Settings: Pattern Tools
I need know what that this option to search synonyms, Im trying the option.

**Comment by arv187** [comment]
I can't figure what mean pattern in this context. Any help?
