### ISSUE TITLE
Bug in 3den-Enchanced: When respawning using save loadout and Task force Radio remove the radio from the player

### ISSUE THREAD

**Issue by Guy-Markman** [RevoArma3/3den-Enhanced-Translation#26]
I'm creating a mission using both 3den-Enchanced and Task Force Radio and I got the next problem:
I use "Save loadout" option from 3den Enchanced and also use Task Force Radio.
Everytime a player respawn, he respawn with everything he had except the radio, whice get removed.

I posted it over here because I saw that you are the creator of the mod, and I need some help in this.

**Comment by RevoArma3** [comment]
Hey,
thanks for the bug report. However, this issue is related to TFAR and how it adds the radios. I am sure you can find help via google or the BIS Forums.
